name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Print a message
          run: echo "This workflow was triggered by a repository_dispatch event."
