name: Trigger Workflow in Another Repo

on:
  repository_dispatch:
    types: [execute-workflow]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: ajay55670/gts  
          ref: main  
      - name: Execute YAML File
        run: |
          # Execute your YAML file here
